/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3_200516672_Silva;
import java.util.Date;
import java.util.ArrayList;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Acceso acceso1 = new Acceso("Juan", true, false, true);
        Acceso acceso2 = new Acceso("Juan", false, true, false);
        Date fecha = new Date();
        String onlineUser = "Pedro";
        Documento doc1 = new Documento(0,"Documento1","Texto1",fecha,fecha);
        System.out.println("### EDITOR COLABORATIVO ###\n" +
                            "## Registrado como: "+ onlineUser + " ##\n" +
                            "Escoja su opción:\n" +
                            "1. Crear nuevo documento\n" +
                            "2. Compartir documento\n" +
                            "3. Agregar contenido a un documento\n" +
                            "4. Restaurar versión de un documento\n" +
                            "5. Revocar acceso a un documento\n" +
                            "6. Buscar en los documentos\n" +
                            "7. Visualizar documentos\n" +
                            "8. Cerrar sesión\n" +
                            "9. Cerrar el programa\n" +
                            "INTRODUZCA SU OPCIÓN: _ ");
    }
}
