/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3_200516672_Silva;
import java.util.Date;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;

/**
 *
 * @author Matias
 */
public class App {

    /**
     *
     * @param args
     */
    public static void main(String[] args) {
        Controlador controller = new Controlador();
        controller.Menu();
        
    }
}
